require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
# require_relative '../node_modules/react-native-permissions/scripts/setup'


platform :ios, '10.0'

pod 'Firebase/Messaging'
pod 'YogaKit'
pod 'Firebase/Crashlytics', '~> 7.6.0'
target 'dashboard' do

  # permissions_path = '../node_modules/react-native-permissions/ios'
  # pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # pod 'RNFBApp',:path => ' ../node_modules/@react-native-firebase/app'
  # pod 'RNFBMessaging',:path => ' ../node_modules/@react-native-firebase/messaging'

  target 'dashboardTests' do
    inherit! :complete
    # Pods for testing
  end

  puts("Image fix for ios14: remove this when upgrading to >=  0.63.3")
find = "_currentFrame.CGImage;"
replace = "_currentFrame.CGImage ;} else < [super displayLayer:layer];"
op = `sed -i '' -e "s/#{find}/#{replace}/g" ../node_modules/react-native/Libraries/Image/RCTUIImageViewAnimated.m`
puts("Image fix for ios14 done")


  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    flipper_post_install(installer)
  end
end
end
end

# post_install do |installer|
 
#     end
#   end
# end


target 'dashboard-tvOS' do
  # Pods for dashboard-tvOS

  target 'dashboard-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

